### PR TITLE
Enable build for ppc and arm

### PR DESCRIPTION
**Pull request by ksangeek**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

PR to enable build for ppc64le and arm. Thank you!

### CODE REVIEW

**Comment by lmcinnes** [comment]
Thanks for working on this -- I hadn't thought to try to get it working (and don't know much about how to do so) but I would definitely appreciate it if it does. At a glance it looks like the Numba dependency isn't working yet. Hopefully that's not too big a stumbling block.

**Comment by ksangeek** [comment]
Hi @lmcinnes Thanks for your review.
I see that the numba dependency issue is with `linux-aarch64`. However, the build for `linux-ppc64le` goes through fine. I'll try to enable the numba build for aarch64 and see if this can be fixed - https://github.com/conda-forge/numba-feedstock.

**Comment by ksangeek** [comment]
I see that the failure for dependency packages `llvm` / `llvmlite` from conda-forge is causing issues to get the build of `numba` for `linux-aarch64` - https://github.com/conda-forge/numba-feedstock/pull/40.
While getting those resolved could take more time, @lmcinnes if you are fine can we proceed with enabling builds for `linux-ppc64le`.

**Comment by lmcinnes** [comment]
Looks good to me. Thanks!

**Pull request merged**
